import React from 'react'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js',
  description: "Generated by create next app",
}

export default function Messages() {
  return (
    <div>
      <div className='flex justify-center items-center w-[95%] mx-auto mt-24'>
        messages
      </div>
    </div>
  )
}
