import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import Navbar from "@/components/Navbar";
import LogoutModal from "@/components/LogoutModal";
import { getServerSession } from "next-auth";
import SessionProvider from '@/components/SessionProvider'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Devoro | Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <html lang="en" className="bg-gray-100">
      <head>
        <link
            rel="icon"
            href="/Devoro-logo-mobile.png"
            type="image/<generated>"
            sizes="<generated>"
          />
      </head>
      <body className={`${inter.className} md:w-[800px] lg:w-[1000px] xl:w-[700px] mx-auto lg:mr-auto`}>
          <SessionProvider session={session}>
            <div className="flex">
              <div>
                <LeftSidebar />
              </div>
              <div className="flex flex-col md:w-[80%] sm:w-full lg:w-full w-full h-auto">
                <Navbar />
                {children}
              </div> 
              <div className="hidden lg:block">
                <RightSidebar />
              </div>
            </div>
            <div className="z-50 absolute top-[450px] left-1/2 transform -translate-x-1/2 -translate-y-1/2">
              <LogoutModal />  
            </div>
          </SessionProvider>
      </body>
    </html>
  );
}




